# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: 3

vars:
  EPOCH: '946684800' # 2000-01-01T00:00:00Z
  STAMP: '200001010000' # 2000-01-01T00:00:00Z

  DIR: '{{.DIR | default .USER_WORKING_DIR}}'  # Path to the Poetry project to bundle
  OUT: '{{.OUT | default "./lambda_build"}}'  # ! relative to DIR !

  IMAGE: '{{.IMAGE | default "public.ecr.aws/sam/build-python3.12"}}'  # Target your desired Lambda runtime
  PLATFORM: '{{.PLATFORM | default "linux/amd64"}}'  # Target your desired Lambda runtime platform, NOT your development platform

  CODE_ZIP_LEVEL: '{{.CODE_ZIP_LEVEL | default "0"}}' # code compression: 0=store (no compression), 6=medium, 9=max
  LAYER_ZIP_LEVEL: '{{.LAYER_ZIP_LEVEL | default "0"}}' # layer compression: 0=store (no compression), 6=medium 9=max

  PRECOMPILE: '{{.PRECOMPILE | default "true"}}'  # whether to generate .pyc's - on: slightly faster Lambda cold starts, off: faster bundling
  INVALIDATION_MODE: '{{.INVALIDATION_MODE | default "unchecked-hash"}}'  # checked-hash is slower, but technically 'safer'. Read Python docs!

set: [pipefail]
shopt: [globstar]

# output:
#   group:
#     begin: "::group::{{.TASK}} ({{.DIR}})"
#     end: "::endgroup::"
#     error_only: false

tasks:
  clean:
    dir: "{{.DIR}}"
    cmds:
      - rm -rf "{{.OUT}}"
      - mkdir -p "{{.OUT}}/code"
      - mkdir -p "{{.OUT}}/layer/python"

  export:
    deps: [clean]
    dir: "{{.DIR}}"
    cmds:
      - poetry export --without-hashes --format=requirements.txt --output "{{.OUT}}/requirements.txt"
      - grep -Ev 'file://' "{{.OUT}}/requirements.txt" > "{{.OUT}}/requirements-remote.txt"
      - touch "{{.OUT}}/requirements-local.txt"
      - cmd: grep -E 'file://' "{{.OUT}}/requirements.txt" | sed -E 's/^-e //' > "{{.OUT}}/requirements-local.txt"
        ignore_error: true

  build-code:
    dir: "{{.DIR}}"
    cmds:
      - |
        pip install . -r "{{.OUT}}/requirements-local.txt" --no-deps --target "{{.OUT}}/code" {{if eq .PRECOMPILE "false"}}--no-compile{{end}}
      - |
        docker run --rm \
          --platform {{.PLATFORM}} \
          -v {{.OUT}}:/opt/build \
          {{.IMAGE}} \
          bash -c 'set -euo pipefail; \
            export PYTHONHASHSEED=0 SOURCE_DATE_EPOCH={{.EPOCH}}; \
            if [ "{{.PRECOMPILE}}" = "true" ]; then \
              python -m compileall -q -f --invalidation-mode={{.INVALIDATION_MODE}} -d /var/task /opt/build/code; \
            else \
              find /opt/build/code -name "__pycache__" -type d -prune -exec rm -rf {} +; \
              find /opt/build/code -name '*.pyc' -delete; \
            fi'
      - |
        if [ "{{.PRECOMPILE}}" = "false" ]; then
          find "{{.OUT}}/code" -name "__pycache__" -type d -prune -exec rm -rf {} +
          find "{{.OUT}}/code" -name '*.pyc' -delete
        fi
      - find "{{.OUT}}/code" -type f -exec touch -t {{.STAMP}} {} +
      - (cd "{{.OUT}}/code" && LC_ALL=C find . -type f | sort | zip -X -q -{{.CODE_ZIP_LEVEL}} ../code.zip -@)

  build-layer:
    dir: "{{.DIR}}"
    cmds:
      - |
        docker run --rm \
          --platform {{.PLATFORM}} \
          -v {{.OUT}}:/opt/build \
          {{.IMAGE}} \
          bash -c 'set -euo pipefail; \
            pip install --no-cache-dir {{if eq .PRECOMPILE "false"}}--no-compile{{end}} -r /opt/build/requirements-remote.txt -t /opt/build/layer/python; \
            export PYTHONHASHSEED=0 SOURCE_DATE_EPOCH={{.EPOCH}}; \
            if [ "{{.PRECOMPILE}}" = "true" ]; then \
              python -m compileall -q -f --invalidation-mode={{.INVALIDATION_MODE}} -d /opt/python /opt/build/layer/python; \
            else \
              find /opt/build/layer/python -name "__pycache__" -type d -prune -exec rm -rf {} +; \
              find /opt/build/layer/python -name '*.pyc' -delete; \
            fi'
      - |
        if [ "{{.PRECOMPILE}}" = "false" ]; then
          find "{{.OUT}}/layer" -name "__pycache__" -type d -prune -exec rm -rf {} +
          find "{{.OUT}}/layer" -name '*.pyc' -delete
        fi
      - find "{{.OUT}}/layer" -type f -exec touch -t {{.STAMP}} {} +
      - (cd "{{.OUT}}/layer" && LC_ALL=C find . -type f | sort | zip -X -q -{{.LAYER_ZIP_LEVEL}} ../layer.zip -@)

  bundle:
    dir: "{{.DIR}}"
    cmds:
      - cmd: 'echo "DIR: {{.DIR}}, OUT: {{.OUT}}, PWD: $(pwd)"'
      - task: export
      - task: bundle-parallel

  default:
    cmds:
      - task: bundle

  bundle-parallel:
    internal: true
    deps: [build-code, build-layer]
