[tool.poetry]
name = "a"
version = "0.1.0"
description = ""
authors = ["Xavier Bergeron <xavbergeron@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
b = { path = "../b", develop = true }

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.8"
poetry-plugin-bundle = ">=1.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
# Check this first even if it spits out warnings and maybe slows down package resolution
# Otherwise someone could publish `xoipy` on PyPI and we'd get theirs installed instead of ours
# TODO with Poetry 2.0: specify `source` along with `version` on all internal packages
#      (including xoi-python-packages)
name = "xoi"
priority = "primary"
url = "https://xoi.jfrog.io/artifactory/api/pypi/python/simple"

[[tool.poetry.source]]
name = "pypi"
priority = "supplemental"
