[tool.poetry]
name = "b"
version = "0.1.0"
description = ""
authors = ["Xavier Bergeron <xavbergeron@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
c = { path = "../c", develop = true }
pydantic = "^2.11.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "pypi"
priority = "primary"
